### ISSUE TITLE
How to make template for text

### ISSUE THREAD

**Issue by minhluan259** [tomgrohl/jCountdown#12]
Ex: template: '&lt;div>&lt;span class="hour">%h&lt;/span>&lt;span class="text-hour">%text-h</span&gt;</div&gt;'

**Comment by tomgrohl** [comment]
Hi

I'm not sure what you mean. Are you wanting to have placholders for both the hour number and the hour text?

**Comment by minhluan259** [comment]
Yes, i want to have placeholders for both number and text. %y %text-y, %m %text-m, %w %text-m, ...

**Comment by tomgrohl** [comment]
Currently this can't be done. Setting your own template is meant to be simple and only the date and time placeholders are provided.

**Comment by tomgrohl** [comment]
Opened issue #13 Would be good to add this support.
