### ISSUE TITLE
Add template support for text placeholders

### ISSUE THREAD

**Issue by tomgrohl** [tomgrohl/jCountdown#13]
Would be good to add support so placeholders can be added for 'hours' etc text. 

Might do this for version 1.6.0 so the templating can be simplified.

**Comment by minhluan259** [comment]
Please tell me, when you update enhancement ? Thanks.

**Comment by tomgrohl** [comment]
I've been busy with other projects. I'm still going over implementing this feature. For version 2.0 id like to only have 1 way of doing templating rather than 2. 

There might be a way of doing it with the current version. I'll knock up a example for you and add it to the demos.

**Comment by tomgrohl** [comment]
I've added a new demo: https://github.com/tomgrohl/jCountdown/blob/master/demo/advanced-template.html

You will see from the settings how you can set a template. It will add in the hours numbers and text for you.

**Comment by minhluan259** [comment]
Thank @tomgrohl. But I want like this: 
![capture](https://cloud.githubusercontent.com/assets/7834473/7782839/72e4893c-0155-11e5-92af-9f8e0669b280.PNG)
How I do? :)

**Comment by tomgrohl** [comment]
This can't be done with either template functionality. Thats why I was going to leave it until version 2.0.

It would be a breaking change to add in this functionality. I can only suggest to use another plugin or edit the template you need.

**Comment by minhluan259** [comment]
Ok. Thank again. I was used another plugin but I love your plugin. I'll waiting for v2.

**Comment by tomgrohl** [comment]
Glad you like it. 

I've started version 2.0 this morning and made a lot or progress. Tests are still passing so its looking good. 

I'm using your examples as a base for improving the templating. I think thats how complex it could get.

**Comment by tomgrohl** [comment]
Quick update. Making good progress. Refactored a bit of code including templating. Currently still testing and rewriting the demos for version 2.0.

**Comment by minhluan259** [comment]
:+1: Great progress :)

**Comment by tomgrohl** [comment]
Version 2.0.0 is now up. With updated demos, fixes and the new templating.

If you look at this demo (https://github.com/tomgrohl/jCountdown/blob/master/demo/locale.html) you can see how to do the templating you want.

**Comment by minhluan259** [comment]
![capture](https://cloud.githubusercontent.com/assets/7834473/8396932/920dd70e-1de4-11e5-84ad-2a05a9d61cbe.PNG)
Bug when install with bower.
Please remove , on "changelog.txt", in bower.json file.

**Comment by tomgrohl** [comment]
This has now been fixed.
